#!/bin/sh
set -e

case "$1" in
    configure)
    if ! getent group nastools-homeassistant >/dev/null 2>&1; then
        rn_nml -a group:nastools-homeassistant
    fi
    if ! getent passwd nastools-homeassistant >/dev/null 2>&1; then
        rn_nml -a user:nastools-homeassistant:nastools-homeassistant
    fi
    chown -R nastools-homeassistant:nastools-homeassistant /apps/nastools-homeassistant
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
